/**
    @file

    @brief
        This program is used to upload a configuration the si5395 chip 
		Chip on the SYNCx5104.

    @verbatim

		This Program file accepts a configuration file generated by ClockBuilderPro
		exported as a *.csv format, and will attempt to configure a si5395 chip. 
		The program will look for the USB connection. This program requires super
		user privledges by default.
		
		Example Usage:
			./si5395_prog [configuration file]
			./si5395_prog cfg/si5395_configuration_example.txt
		

    @endverbatim

    @verbatim
    --------------------------------------------------------------------------
    This file and its contents are copyright (C) RTD Embedded Technologies,
    Inc.  All Rights Reserved.

    This software is licensed as described in the RTD End-User Software License
    Agreement.  For a copy of this agreement, refer to the file LICENSE.TXT
    (which should be included with this software) or contact RTD Embedded
    Technologies, Inc.
    --------------------------------------------------------------------------
    @endverbatim

    $Id: si5395_prog.cpp 154544 2026-05-20 20:26:38Z Nsmith $
*/  
    
#if defined _WIN32 || defined _WIN64
#include <windows.h>
#endif /*  */
    
#if defined __unix__
#include <unistd.h>
int Sleep(int msec)  { return usleep(1000 * msec);
}

 
#endif /*  */
    
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
#include <string>
#include <fstream>
    
//------------------------------------------------------------------------------
// include FTDI libraries
//
#include "ftd2xx.h"
#include "libft4222.h"
    
#include "si5395_types.h"
    
//#define SIM
    std::vector < FT_DEVICE_LIST_INFO_NODE > g_FT4222DevList;
typedef uint8_t si5395_spi_data_t;
 
/**
 * @brief Extract page number from SI5395 address
 * @param[in] address Address
 * @return Page number
 */ 
static inline si5395_reva_page_t si5395_address2page(si5395_reva_address_t
						     address)  {
	return ((address >> 8) & 0xFF);
}

 
/**
 * @brief Extract offset from SI5395 address
 * @param[in] address Address
 * @return Offset inside the page
 */ 
static inline si5395_reva_offset_t si5395_address2offs(si5395_reva_address_t
						       address)  {
	return (address & 0xFF);
}

 
/**
 * @brief Create register vector from file
 * @param[in] input filename
 * @return register vector
 */ 
    std::vector < si5395_reva_register_t >
si5395_regfile_parse(std::string fname)  { std::ifstream regfile(fname);
	std::string str;
	si5395_reva_register_t reg;
	std::vector < si5395_reva_register_t > cfg_regs;
	 while (std::getline(regfile, str))
		 {
		
		    // line is a comment
		    if (str[0] != '0')
			 {
			continue;
			}
		
		else
			 {
			
			    // parse the values
			    //printf("parsing line:%s\n", str.c_str());
			    reg.address = std::stoi(str.substr(0, 6), NULL, 0);
			reg.value = std::stoi(str.substr(7, 4), NULL, 0);
			 
			    // add the register to the vector
			    cfg_regs.push_back(reg);
			 
			    //printf("cfg pushed back 0x%x, 0x%x\n", reg.address, reg.value );
			}
		}
	return cfg_regs;
}

 
/**
 * @brief Convert register vector values into SPI commands
 * @param[in] regs Register values
 * @param[out] cmd SPI commands
 * @return Number of SPI commands created
 * @details
 * The function creates a sequence of SPI data bytes to transfer to the
 * SI5395 that programs the registers of the chip. An internal state 
 * machine is utilized in order to make efficient use of the bytes to
 * transfer.
 */ 
size_t si5395_regvec2commands(std::vector < si5395_reva_register_t > regs,
			      si5395_spi_data_t *cmd)  { size_t reg_idx = 0;
	size_t cmd_idx = 0;
	 si5395_reva_offset_t cur_offs = 0, reg_offs = 0;
	si5395_reva_page_t cur_page = 0, reg_page = 0;
 for (auto reg:regs) {
		reg_page = si5395_address2page(reg.address);
		reg_offs = si5395_address2offs(reg.address);
		 if (reg_idx == 0 || reg_page != cur_page) {
			cmd[cmd_idx++] = SI5395_SPI_COMMAND_SET_ADDR;
			cmd[cmd_idx++] = SI5395_ADDR_PAGE_REGISTER;
			cmd[cmd_idx++] = SI5395_SPI_COMMAND_WRITE_INC;
			cmd[cmd_idx++] = reg_page;
			cur_page = reg_page;
			
			    // Current offset is the offset of page register
			    cur_offs = SI5395_ADDR_PAGE_REGISTER;
		}
		 
		    // Add a set address command if the offset needs to be changed
		    if (reg_offs != cur_offs + 1) {
			cmd[cmd_idx++] = SI5395_SPI_COMMAND_SET_ADDR;
			cmd[cmd_idx++] = reg_offs;
		}
		 
		    // Write the data
		    cmd[cmd_idx++] = SI5395_SPI_COMMAND_WRITE_INC;
		cmd[cmd_idx++] = reg.value;
		cur_offs = reg_offs;
		reg_idx++;
	}
	 return cmd_idx;
}

   
//------------------------------------------------------------------------------
    inline std::string DeviceFlagToString(DWORD flags)  { std::string msg;
	msg += (flags & 0x1) ? "DEVICE_OPEN" : "DEVICE_CLOSED";
	msg += ", ";
	msg += (flags & 0x2) ? "High-speed USB" : "Full-speed USB";
	return msg;
}
 void ListFtUsbDevices()  { FT_STATUS ftStatus = 0;
	 DWORD numOfDevices = 0;
	ftStatus = FT_CreateDeviceInfoList(&numOfDevices);
	 for (DWORD iDev = 0; iDev < numOfDevices; ++iDev)
		 {
		FT_DEVICE_LIST_INFO_NODE devInfo;
		memset(&devInfo, 0, sizeof(devInfo));
		 ftStatus =
		    FT_GetDeviceInfoDetail(iDev, &devInfo.Flags, &devInfo.Type,
					   &devInfo.ID, &devInfo.LocId,
					   devInfo.SerialNumber,
					   devInfo.Description,
					   &devInfo.ftHandle);
		 if (FT_OK == ftStatus)
			 {
			printf("Dev %d:\n", iDev);
			printf("  Flags= 0x%x, (%s)\n", devInfo.Flags,
				DeviceFlagToString(devInfo.Flags).c_str());
			printf("  Type= 0x%x\n", devInfo.Type);
			printf("  Vendor ID= 0x%04x\n",
				(devInfo.ID & 0xFFFF0000) >> 16);
			printf("  Device ID= 0x%04x\n",
				(devInfo.ID & 0x0000FFFF) >> 0);
			printf("  LocId= 0x%x\n", devInfo.LocId);
			printf("  SerialNumber= %s\n", devInfo.SerialNumber);
			printf("  Description= %s\n", devInfo.Description);
			printf("  ftHandle= 0x%p\n", devInfo.ftHandle);
			 const std::string desc = devInfo.Description;
			if (desc == "FT4222" || desc == "FT4222 A")
				 {
				g_FT4222DevList.push_back(devInfo);
				}
			}
		}
}
	 void print_buffer(uint8_t *buf, size_t len) 
    { for (size_t i = 0; i < len; ++i) {
		printf("%02x ", buf[i]);
		if (i % 16 == 15)
			printf("\n");
	}
	printf("\n");
}

 
//------------------------------------------------------------------------------
// main
//------------------------------------------------------------------------------
int main(int argc, char const *argv[])  {  
	    /* Simple argument parsing */ 
	    if (argc != 2) {
			    printf("usage: %s FILE\n", argv[0]); return -1; }
			     std::string filename(argv[1]);  
			    //todo handle input file name and device number
			    auto cfg_regs = si5395_regfile_parse(filename);  
#ifndef SIM
			    ListFtUsbDevices();  if (g_FT4222DevList.empty()) {
			    printf("No FT4222 device is found!\n"); return 0; }
			     FT_HANDLE ftHandle = NULL; FT_STATUS ftStatus;
			    ftStatus =
			    FT_OpenEx(reinterpret_cast < PVOID >
				      (g_FT4222DevList[0].LocId),
				      FT_OPEN_BY_LOCATION, &ftHandle);
			    if (FT_OK != ftStatus) {
			    printf("Open a FT4222 device failed!\n");
			    return 0; }
			     printf("\n\n");
			    printf("Init FT4222 as SPI master\n");
			    ftStatus =
			    FT4222_SPIMaster_Init(ftHandle, SPI_IO_SINGLE,
						  CLK_DIV_256, CLK_IDLE_LOW,
						  CLK_LEADING, 0x01);
			    if (FT_OK != ftStatus) {
			    printf
			    ("Init FT4222 as SPI master device failed!\n");
			    return 0; }
			    
#endif /*  */
			    
			    // Translate the register values to SPI commands
			    size_t spi_data_len = 8192;
			    si5395_spi_data_t * spi_data =
			    (si5395_spi_data_t *) malloc(spi_data_len *
							 sizeof
							 (si5395_spi_data_t));
			    si5395_spi_data_t * spi_data_rb =
			    (si5395_spi_data_t *) malloc(spi_data_len *
							 sizeof
							 (si5395_spi_data_t));
			     size_t num_data; uint16_t transferred;
			     uint8_t commands[] = { 
			    // Set page register to 0
			    SI5395_SPI_COMMAND_SET_ADDR,
			    SI5395_ADDR_PAGE_REGISTER,
			    SI5395_SPI_COMMAND_WRITE_DATA, 0x00, 
			    // Read back the page regsiter
			    SI5395_SPI_COMMAND_READ_DATA, 0xFF, 
			    // Set address to part number register and read the two bytes
			    SI5395_SPI_COMMAND_SET_ADDR,
			    SI5395_ADDR_PN_BASE_LOW,
			    SI5395_SPI_COMMAND_READ_INC, 0xFF,
			    SI5395_SPI_COMMAND_READ_INC, 0xFF, 
			    // Read the device grade and device revision
			    SI5395_SPI_COMMAND_READ_INC, 0xFF,
			    SI5395_SPI_COMMAND_READ_INC, 0xFF 
			    };
			     uint8_t commands_rb[sizeof(commands) /
						   sizeof(uint8_t)];
			    memset(commands_rb, 0xFF, sizeof(commands_rb));
			     num_data = sizeof(commands) / sizeof(uint8_t);
			     for (size_t i = 0; i < num_data; i += 2) {
			    
#ifndef SIM
			    ftStatus =
			    FT4222_SPIMaster_SingleReadWrite(ftHandle,
							     commands_rb + i,
							     commands + i, 2,
							     &transferred,
							     true);
			    printf("\r%4zd / %4zd ready, status: %d", i + 2,
				    num_data, ftStatus); 
#endif /*  */
			    } printf("\n");  printf("Data sent:\n");
			    print_buffer(commands, num_data);
			     printf("Data readback:\n");
			    print_buffer(commands_rb, num_data);  
			    // Convert the first three commands
			    auto cfg_regs_first3 =
			    std::vector < si5395_reva_register_t >
			    (cfg_regs.begin(), cfg_regs.begin() + 3 + 1);
			    num_data =
			    si5395_regvec2commands(cfg_regs_first3, spi_data);
			     printf
			    ("Transferring config packet of %zd bytes\n",
			     num_data); for (size_t i = 0; i < num_data;
					      i += 2) {
			    
#ifndef SIM
			    ftStatus =
			    FT4222_SPIMaster_SingleWrite(ftHandle, spi_data + i,
							 2, &transferred, true);
			    printf("\r%4zd / %4zd ready, status: %d", i + 2,
				    num_data, ftStatus); 
#endif /*  */
			    } printf("\n");  
			    // Sleep until calibration is completed
			    Sleep(300);  
			    // Convert the other commands
			    auto cfg_regs_main =
			    std::vector < si5395_reva_register_t >
			    (cfg_regs.begin() + 3, cfg_regs.end());
			    num_data =
			    si5395_regvec2commands(cfg_regs_main, spi_data);
			    printf
			    ("Transferring register write packet of %zd bytes\n",
			     num_data); for (size_t i = 0; i < num_data;
					      i += 2) {
			    
#ifndef SIM		
			    ftStatus =
			    FT4222_SPIMaster_SingleWrite(ftHandle, spi_data + i,
							 2, &transferred, true);
			    printf("\r%4zd / %4zd ready, status: %d", i + 2,
				    num_data, ftStatus); 
#endif /*  */
			    } printf("\n");  free(spi_data);
			    free(spi_data_rb); 
#ifndef SIM
			    printf("UnInitialize FT4222\n");
			    FT4222_UnInitialize(ftHandle);
			     printf("Close FT device\n"); FT_Close(ftHandle);
			    
#endif /*  */
			    return 0; }

			    
