/**
    @file

    @brief
        This program is used to upload a configuration the LEA-M8F Ublox 
		Chip on the SYNCx5104. 

    @verbatim

		This Program file accepts a configuration file generated by UCenter
		and will attempt to configre the UBLOX chip on the specified serial port.
		It will attempt to program at the given baud_rate. Use the ubx_set_baudrate
		program prior to this to use a different baud rate than the default 9600.
		This program requires super user priveldges by default to open a serial port.
		
		Example Usage:
			./ubx_config --port /dev/ttyUSB0 --baud_rate 115200 
			--file example_config.txt --save
		

    @endverbatim

    @verbatim
    --------------------------------------------------------------------------
    This file and its contents are copyright (C) RTD Embedded Technologies,
    Inc.  All Rights Reserved.

    This software is licensed as described in the RTD End-User Software License
    Agreement.  For a copy of this agreement, refer to the file LICENSE.TXT
    (which should be included with this software) or contact RTD Embedded
    Technologies, Inc.
    --------------------------------------------------------------------------
    @endverbatim

    $Id: ubx_config.c 154532 2026-05-20 15:56:55Z Nsmith $
*/

#include "serial_port.h"
#include "ubxbuffer.h"
#include "ubxproto.h"
#include "ubxutil.h"

#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>
#include <unistd.h>
#include <string.h>
#include <getopt.h>
int main(int argc, char *argv[])
{
	int baud_rate = 0;
	char *endptr;
	char port_name[100] = { 0 };
	char *file_name = NULL;
	int c;
	static int save;

	while (1) {

		static struct option long_options[] = {
			{ "save", no_argument, &save, 1 },
			{ "port", required_argument, 0, 'p' },
			{ "baud_rate", required_argument, 0, 'b' },
			{ "file", required_argument, 0, 'f' },
			{ "help", no_argument, 0, 'h' },
			{ 0, 0, 0, 0 }
		};
		int options_index = 0;

		c = getopt_long(argc, argv, "pbfh", long_options,
				&options_index);

		if (c == -1)
			break;

		switch (c) {
		case 0:
			{
				if (long_options[options_index].flag != 0)
					break;
				/*printf("option %s",long_options[options_index].name);
				   if (optarg)
				   printf(" with arg %s", optarg);
				   printf("\n"); */
				break;
			}
		case 'p':
			{
				strcpy(port_name, optarg);
				break;
			}
		case 'b':
			{
				baud_rate = strtol(optarg, NULL, 10);
				break;
			}
		case 'f':
			{
				file_name = strdup(optarg);
				break;
			}
		case 'h':
			{
				printf("\n%s\n", argv[0]);
				printf
				    ("\nUsage:%s [--help] [--port /dev/ttyUSB0] [--baud_rate 115200]\n",
				     argv[0]);
				printf
				    ("\t\t\t\t [--file example_config.txt [--save]\n");
				printf
				    ("\n\t --help:\t Display usage information and exit.\n");
				printf
				    ("\n\t --port: \t Set the specified serial port as PORT.\n");
				printf
				    ("\t      PORT:\t\t Port number (/dev/ttyX).\n");
				printf
				    ("\t --baud_rate: \t Set the specified baud rate.\n");
				printf
				    ("\t      BAUD:\t\t Baud rate (9600<=x<=115200).\n");
				printf("\t --file: \t Set the config file.\n");
				printf
				    ("\t      FILE:\t\t Name of the config file.\n");
				printf
				    ("\t --save: Sets the flag to save the configuration file to the flash.\n");
				exit(1);
				break;
			}
		default:
			{
				exit(1);
				break;
			}
		}
	}

	if (baud_rate == 0)
		baud_rate = 115200;
	if (file_name == NULL) {
		file_name = strdup("config.txt");
	}
	if (port_name[0] == 0) {
		strcpy(port_name, "/dev/ttyUSB0");
	}

	ubx_protocol_type_t proto;
	ubx_ring_buffer_t ubx_buffer;

	ubx_buf_init(&ubx_buffer);

	ubx_msg_t ubx_msg;
	port_t port = open_serial_port(port_name, baud_rate);
	printf("Opening serial port: %s ... ", port_name);
	if (port < 0) {
		printf("Could not open serial port\n");
		return 1;
	}
	printf("Success.\n");
	printf("Using baud rate: %d\n", baud_rate);

	// Read configuration file
	uint8_t config_buf[2048];
	size_t n_commands;
	size_t config_size;
	printf("Reading configuration from file: %s ... ", file_name);
	config_size =
	    read_ubx_config_file(file_name, config_buf, sizeof(config_buf),
				 &n_commands);
	printf("Read %ld commands (%ld bytes)\n", n_commands, config_size);

	printf("Uploading configuration commands to GPS:\n");
	int s_commands =
	    upload_ubx_config(port, config_buf, config_size, 1000000, 1);
	printf("Successfully completed: %d of %ld commands\n", s_commands,
	       n_commands);

	if (save) {
		printf("Saving configuration to nonvolatile memory\n");
		save_ubx_config(port);
	}

	free(file_name);

	return 0;
}
